
// List of all country codes and their corresponding flags and names
export const countryCodes = {
  "93": { name: "Afghanistan", flag: "🇦🇫" },
  "355": { name: "Albania", flag: "🇦🇱" },
  "213": { name: "Algeria", flag: "🇩🇿" },
  "1-684": { name: "American Samoa", flag: "🇦🇸" },
  "376": { name: "Andorra", flag: "🇦🇩" },
  "244": { name: "Angola", flag: "🇦🇴" },
  "1-264": { name: "Anguilla", flag: "🇦🇮" },
  "672": { name: "Antarctica", flag: "🇦🇶" },
  "1-268": { name: "Antigua and Barbuda", flag: "🇦🇬" },
  "54": { name: "Argentina", flag: "🇦🇷" },
  "374": { name: "Armenia", flag: "🇦🇲" },
  "297": { name: "Aruba", flag: "🇦🇼" },
  "61": { name: "Australia", flag: "🇦🇺" },
  "43": { name: "Austria", flag: "🇦🇹" },
  "994": { name: "Azerbaijan", flag: "🇦🇿" },
  "1-242": { name: "Bahamas", flag: "🇧🇸" },
  "973": { name: "Bahrain", flag: "🇧🇭" },
  "880": { name: "Bangladesh", flag: "🇧🇩" },
  "1-246": { name: "Barbados", flag: "🇧🇧" },
  "375": { name: "Belarus", flag: "🇧🇾" },
  "32": { name: "Belgium", flag: "🇧🇪" },
  "501": { name: "Belize", flag: "🇧🇿" },
  "229": { name: "Benin", flag: "🇧🇯" },
  "1-441": { name: "Bermuda", flag: "🇧🇲" },
  "975": { name: "Bhutan", flag: "🇧🇹" },
  "591": { name: "Bolivia", flag: "🇧🇴" },
  "387": { name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  "267": { name: "Botswana", flag: "🇧🇼" },
  "55": { name: "Brazil", flag: "🇧🇷" },
  "246": { name: "British Indian Ocean Territory", flag: "🇮🇴" },
  "1-284": { name: "British Virgin Islands", flag: "🇻🇬" },
  "673": { name: "Brunei", flag: "🇧🇳" },
  "359": { name: "Bulgaria", flag: "🇧🇬" },
  "226": { name: "Burkina Faso", flag: "🇧🇫" },
  "257": { name: "Burundi", flag: "🇧🇮" },
  "855": { name: "Cambodia", flag: "🇰🇭" },
  "237": { name: "Cameroon", flag: "🇨🇲" },
  "1": { name: "Canada", flag: "🇨🇦" },
  "238": { name: "Cape Verde", flag: "🇨🇻" },
  "1-345": { name: "Cayman Islands", flag: "🇰🇾" },
  "236": { name: "Central African Republic", flag: "🇨🇫" },
  "235": { name: "Chad", flag: "🇹🇩" },
  "56": { name: "Chile", flag: "🇨🇱" },
  "86": { name: "China", flag: "🇨🇳" },
  "61": { name: "Christmas Island", flag: "🇨🇽" },
  "61": { name: "Cocos Islands", flag: "🇨🇨" },
  "57": { name: "Colombia", flag: "🇨🇴" },
  "269": { name: "Comoros", flag: "🇰🇲" },
  "682": { name: "Cook Islands", flag: "🇨🇰" },
  "506": { name: "Costa Rica", flag: "🇨🇷" },
  "385": { name: "Croatia", flag: "🇭🇷" },
  "53": { name: "Cuba", flag: "🇨🇺" },
  "599": { name: "Curacao", flag: "🇨🇼" },
  "357": { name: "Cyprus", flag: "🇨🇾" },
  "420": { name: "Czech Republic", flag: "🇨🇿" },
  "243": { name: "Democratic Republic of the Congo", flag: "🇨🇩" },
  "45": { name: "Denmark", flag: "🇩🇰" },
  "253": { name: "Djibouti", flag: "🇩🇯" },
  "1-767": { name: "Dominica", flag: "🇩🇲" },
  "1-809": { name: "Dominican Republic", flag: "🇩🇴" },
  "670": { name: "East Timor", flag: "🇹🇱" },
  "593": { name: "Ecuador", flag: "🇪🇨" },
  "20": { name: "Egypt", flag: "🇪🇬" },
  "503": { name: "El Salvador", flag: "🇸🇻" },
  "240": { name: "Equatorial Guinea", flag: "🇬🇶" },
  "291": { name: "Eritrea", flag: "🇪🇷" },
  "372": { name: "Estonia", flag: "🇪🇪" },
  "251": { name: "Ethiopia", flag: "🇪🇹" },
  "500": { name: "Falkland Islands", flag: "🇫🇰" },
  "298": { name: "Faroe Islands", flag: "🇫🇴" },
  "679": { name: "Fiji", flag: "🇫🇯" },
  "358": { name: "Finland", flag: "🇫🇮" },
  "33": { name: "France", flag: "🇫🇷" },
  "689": { name: "French Polynesia", flag: "🇵🇫" },
  "241": { name: "Gabon", flag: "🇬🇦" },
  "220": { name: "Gambia", flag: "🇬🇲" },
  "995": { name: "Georgia", flag: "🇬🇪" },
  "49": { name: "Germany", flag: "🇩🇪" },
  "233": { name: "Ghana", flag: "🇬🇭" },
  "350": { name: "Gibraltar", flag: "🇬🇮" },
  "30": { name: "Greece", flag: "🇬🇷" },
  "299": { name: "Greenland", flag: "🇬🇱" },
  "1-473": { name: "Grenada", flag: "🇬🇩" },
  "1-671": { name: "Guam", flag: "🇬🇺" },
  "502": { name: "Guatemala", flag: "🇬🇹" },
  "44-1481": { name: "Guernsey", flag: "🇬🇬" },
  "224": { name: "Guinea", flag: "🇬🇳" },
  "245": { name: "Guinea-Bissau", flag: "🇬🇼" },
  "592": { name: "Guyana", flag: "🇬🇾" },
  "509": { name: "Haiti", flag: "🇭🇹" },
  "504": { name: "Honduras", flag: "🇭🇳" },
  "852": { name: "Hong Kong", flag: "🇭🇰" },
  "36": { name: "Hungary", flag: "🇭🇺" },
  "354": { name: "Iceland", flag: "🇮🇸" },
  "91": { name: "India", flag: "🇮🇳" },
  "62": { name: "Indonesia", flag: "🇮🇩" },
  "98": { name: "Iran", flag: "🇮🇷" },
  "964": { name: "Iraq", flag: "🇮🇶" },
  "353": { name: "Ireland", flag: "🇮🇪" },
  "44-1624": { name: "Isle of Man", flag: "🇮🇲" },
  "972": { name: "Israel", flag: "🇮🇱" },
  "39": { name: "Italy", flag: "🇮🇹" },
  "225": { name: "Ivory Coast", flag: "🇨🇮" },
  "1-876": { name: "Jamaica", flag: "🇯🇲" },
  "81": { name: "Japan", flag: "🇯🇵" },
  "44-1534": { name: "Jersey", flag: "🇯🇪" },
  "962": { name: "Jordan", flag: "🇯🇴" },
  "7": { name: "Kazakhstan", flag: "🇰🇿" },
  "254": { name: "Kenya", flag: "🇰🇪" },
  "686": { name: "Kiribati", flag: "🇰🇮" },
  "383": { name: "Kosovo", flag: "🇽🇰" },
  "965": { name: "Kuwait", flag: "🇰🇼" },
  "996": { name: "Kyrgyzstan", flag: "🇰🇬" },
  "856": { name: "Laos", flag: "🇱🇦" },
  "371": { name: "Latvia", flag: "🇱🇻" },
  "961": { name: "Lebanon", flag: "🇱🇧" },
  "266": { name: "Lesotho", flag: "🇱🇸" },
  "231": { name: "Liberia", flag: "🇱🇷" },
  "218": { name: "Libya", flag: "🇱🇾" },
  "423": { name: "Liechtenstein", flag: "🇱🇮" },
  "370": { name: "Lithuania", flag: "🇱🇹" },
  "352": { name: "Luxembourg", flag: "🇱🇺" },
  "853": { name: "Macau", flag: "🇲🇴" },
  "389": { name: "Macedonia", flag: "🇲🇰" },
  "261": { name: "Madagascar", flag: "🇲🇬" },
  "265": { name: "Malawi", flag: "🇲🇼" },
  "60": { name: "Malaysia", flag: "🇲🇾" },
  "960": { name: "Maldives", flag: "🇲🇻" },
  "223": { name: "Mali", flag: "🇲🇱" },
  "356": { name: "Malta", flag: "🇲🇹" },
  "692": { name: "Marshall Islands", flag: "🇲🇭" },
  "222": { name: "Mauritania", flag: "🇲🇷" },
  "230": { name: "Mauritius", flag: "🇲🇺" },
  "262": { name: "Mayotte", flag: "🇾🇹" },
  "52": { name: "Mexico", flag: "🇲🇽" },
  "691": { name: "Micronesia", flag: "🇫🇲" },
  "373": { name: "Moldova", flag: "🇲🇩" },
  "377": { name: "Monaco", flag: "🇲🇨" },
  "976": { name: "Mongolia", flag: "🇲🇳" },
  "382": { name: "Montenegro", flag: "🇲🇪" },
  "1-664": { name: "Montserrat", flag: "🇲🇸" },
  "212": { name: "Morocco", flag: "🇲🇦" },
  "258": { name: "Mozambique", flag: "🇲🇿" },
  "95": { name: "Myanmar", flag: "🇲🇲" },
  "264": { name: "Namibia", flag: "🇳🇦" },
  "674": { name: "Nauru", flag: "🇳🇷" },
  "977": { name: "Nepal", flag: "🇳🇵" },
  "31": { name: "Netherlands", flag: "🇳🇱" },
  "599": { name: "Netherlands Antilles", flag: "🇳🇱" },
  "687": { name: "New Caledonia", flag: "🇳🇨" },
  "64": { name: "New Zealand", flag: "🇳🇿" },
  "505": { name: "Nicaragua", flag: "🇳🇮" },
  "227": { name: "Niger", flag: "🇳🇪" },
  "234": { name: "Nigeria", flag: "🇳🇬" },
  "683": { name: "Niue", flag: "🇳🇺" },
  "672": { name: "Norfolk Island", flag: "🇳🇫" },
  "850": { name: "North Korea", flag: "🇰🇵" },
  "47": { name: "Norway", flag: "🇳🇴" },
  "968": { name: "Oman", flag: "🇴🇲" },
  "92": { name: "Pakistan", flag: "🇵🇰" },
  "680": { name: "Palau", flag: "🇵🇼" },
  "970": { name: "Palestine", flag: "🇵🇸" },
  "507": { name: "Panama", flag: "🇵🇦" },
  "675": { name: "Papua New Guinea", flag: "🇵🇬" },
  "595": { name: "Paraguay", flag: "🇵🇾" },
  "51": { name: "Peru", flag: "🇵🇪" },
  "63": { name: "Philippines", flag: "🇵🇭" },
  "48": { name: "Poland", flag: "🇵🇱" },
  "351": { name: "Portugal", flag: "🇵🇹" },
  "1-787": { name: "Puerto Rico", flag: "🇵🇷" },
  "974": { name: "Qatar", flag: "🇶🇦" },
  "242": { name: "Republic of the Congo", flag: "🇨🇬" },
  "262": { name: "Reunion", flag: "🇷🇪" },
  "40": { name: "Romania", flag: "🇷🇴" },
  "7": { name: "Russia", flag: "🇷🇺" },
  "250": { name: "Rwanda", flag: "🇷🇼" },
  "590": { name: "Saint Barthelemy", flag: "🇧🇱" },
  "290": { name: "Saint Helena", flag: "🇸🇭" },
  "1-869": { name: "Saint Kitts and Nevis", flag: "🇰🇳" },
  "1-758": { name: "Saint Lucia", flag: "🇱🇨" },
  "590": { name: "Saint Martin", flag: "🇲🇫" },
  "508": { name: "Saint Pierre and Miquelon", flag: "🇵🇲" },
  "1-784": { name: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  "685": { name: "Samoa", flag: "🇼🇸" },
  "378": { name: "San Marino", flag: "🇸🇲" },
  "239": { name: "Sao Tome and Principe", flag: "🇸🇹" },
  "966": { name: "Saudi Arabia", flag: "🇸🇦" },
  "221": { name: "Senegal", flag: "🇸🇳" },
  "381": { name: "Serbia", flag: "🇷🇸" },
  "248": { name: "Seychelles", flag: "🇸🇨" },
  "232": { name: "Sierra Leone", flag: "🇸🇱" },
  "65": { name: "Singapore", flag: "🇸🇬" },
  "421": { name: "Slovakia", flag: "🇸🇰" },
  "386": { name: "Slovenia", flag: "🇸🇮" },
  "677": { name: "Solomon Islands", flag: "🇸🇧" },
  "252": { name: "Somalia", flag: "🇸🇴" },
  "27": { name: "South Africa", flag: "🇿🇦" },
  "82": { name: "South Korea", flag: "🇰🇷" },
  "211": { name: "South Sudan", flag: "🇸🇸" },
  "34": { name: "Spain", flag: "🇪🇸" },
  "94": { name: "Sri Lanka", flag: "🇱🇰" },
  "249": { name: "Sudan", flag: "🇸🇩" },
  "597": { name: "Suriname", flag: "🇸🇷" },
  "268": { name: "Swaziland", flag: "🇸🇿" },
  "46": { name: "Sweden", flag: "🇸🇪" },
  "41": { name: "Switzerland", flag: "🇨🇭" },
  "963": { name: "Syria", flag: "🇸🇾" },
  "886": { name: "Taiwan", flag: "🇹🇼" },
  "992": { name: "Tajikistan", flag: "🇹🇯" },
  "255": { name: "Tanzania", flag: "🇹🇿" },
  "66": { name: "Thailand", flag: "🇹🇭" },
  "228": { name: "Togo", flag: "🇹🇬" },
  "690": { name: "Tokelau", flag: "🇹🇰" },
  "676": { name: "Tonga", flag: "🇹🇴" },
  "1-868": { name: "Trinidad and Tobago", flag: "🇹🇹" },
  "216": { name: "Tunisia", flag: "🇹🇳" },
  "90": { name: "Turkey", flag: "🇹🇷" },
  "993": { name: "Turkmenistan", flag: "🇹🇲" },
  "1-649": { name: "Turks and Caicos Islands", flag: "🇹🇨" },
  "688": { name: "Tuvalu", flag: "🇹🇻" },
  "256": { name: "Uganda", flag: "🇺🇬" },
  "380": { name: "Ukraine", flag: "🇺🇦" },
  "971": { name: "United Arab Emirates", flag: "🇦🇪" },
  "44": { name: "United Kingdom", flag: "🇬🇧" },
  "1": { name: "United States", flag: "🇺🇸" },
  "598": { name: "Uruguay", flag: "🇺🇾" },
  "998": { name: "Uzbekistan", flag: "🇺🇿" },
  "678": { name: "Vanuatu", flag: "🇻🇺" },
  "379": { name: "Vatican", flag: "🇻🇦" },
  "58": { name: "Venezuela", flag: "🇻🇪" },
  "84": { name: "Vietnam", flag: "🇻🇳" },
  "681": { name: "Wallis and Futuna", flag: "🇼🇫" },
  "967": { name: "Yemen", flag: "🇾🇪" },
  "260": { name: "Zambia", flag: "🇿🇲" },
  "263": { name: "Zimbabwe", flag: "🇿🇼" }
};
